[[redirects]]
  from = "https://demo-bank-statement.netlify.app/api/v1/bsc/convert"
  to = "http://64.227.141.56:8080/api/v1/bsc/convert"
  status = 301
  force = true
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
